using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace FunctionalStateMachine.Core.Generator;

[Generator]
public sealed class TriggerTypeGenerator : IIncrementalGenerator
{
    private const string CreateMethodName = "Create";
    // StateMachine<TState, TTrigger, TData, TCommand> — the 4-param with-data variant
    private const string StateMachineMetadataName4 = "StateMachine`4";
    // StateMachine<TState, TTrigger, TCommand> — the 3-param NoData variant
    private const string StateMachineMetadataName3 = "StateMachine`3";
    private const string StateMachineNamespace = "FunctionalStateMachine.Core";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var triggerTypes = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => IsCreateInvocation(node),
                static (ctx, _) => GetTriggerType(ctx))
            .Where(static symbol => symbol is not null)
            .Select(static (symbol, _) => symbol!)
            .Collect();

        var combined = triggerTypes.Combine(context.CompilationProvider);
        context.RegisterSourceOutput(combined, static (ctx, data) =>
        {
            var (triggerTypeSymbols, compilation) = data;
            if (triggerTypeSymbols.IsDefaultOrEmpty)
            {
                return;
            }

            Generate(ctx, compilation, triggerTypeSymbols);
        });
    }

    private static bool IsCreateInvocation(SyntaxNode node)
    {
        if (node is not InvocationExpressionSyntax invocation)
        {
            return false;
        }

        return invocation.Expression is MemberAccessExpressionSyntax
        {
            Name: { Identifier.ValueText: CreateMethodName }
        };
    }

    private static INamedTypeSymbol? GetTriggerType(GeneratorSyntaxContext context)
    {
        if (context.Node is not InvocationExpressionSyntax invocation)
        {
            return null;
        }

        var symbolInfo = context.SemanticModel.GetSymbolInfo(invocation);
        if (symbolInfo.Symbol is not IMethodSymbol { Name: CreateMethodName } methodSymbol)
        {
            return null;
        }

        var containingType = methodSymbol.ContainingType;
        if (containingType is null)
        {
            return null;
        }

        // Match both 4-param (with data) and 3-param (NoData) StateMachine
        var metadataName = containingType.OriginalDefinition.MetadataName;
        if (!string.Equals(metadataName, StateMachineMetadataName4, StringComparison.Ordinal) &&
            !string.Equals(metadataName, StateMachineMetadataName3, StringComparison.Ordinal))
        {
            return null;
        }

        if (!string.Equals(
                containingType.ContainingNamespace?.ToDisplayString(),
                StateMachineNamespace,
                StringComparison.Ordinal))
        {
            return null;
        }

        // TTrigger is always the 2nd type argument (index 1)
        if (containingType.TypeArguments.Length < 2)
        {
            return null;
        }

        return containingType.TypeArguments[1] as INamedTypeSymbol;
    }

    private static void Generate(
        SourceProductionContext context,
        Compilation compilation,
        IReadOnlyList<INamedTypeSymbol> triggerBaseTypes)
    {
        // Only generate if [ModuleInitializer] is available in the target framework
        var moduleInitAttr = compilation.GetTypeByMetadataName(
            "System.Runtime.CompilerServices.ModuleInitializerAttribute");
        if (moduleInitAttr is null)
        {
            return;
        }

        // Collect all types in the current assembly (including nested)
        var allTypes = new List<INamedTypeSymbol>();
        CollectTypes(compilation.Assembly.GlobalNamespace, allTypes);

        // Deduplicate trigger base types
        var uniqueTriggerTypes = new List<INamedTypeSymbol>();
        var seen = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
        foreach (var t in triggerBaseTypes)
        {
            if (seen.Add(t))
            {
                uniqueTriggerTypes.Add(t);
            }
        }

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("using System;");
        source.AppendLine("using System.Runtime.CompilerServices;");
        source.AppendLine("using FunctionalStateMachine.Core;");
        source.AppendLine();
        source.AppendLine("namespace FunctionalStateMachine.Core.Generated");
        source.AppendLine("{");
        source.AppendLine("    internal static class TriggerTypeRegistrationBootstrap");
        source.AppendLine("    {");
        source.AppendLine("        [ModuleInitializer]");
        source.AppendLine("        internal static void Initialize()");
        source.AppendLine("        {");

        foreach (var triggerBaseType in uniqueTriggerTypes)
        {
            // Skip trigger types that are not accessible from the generated module initializer
            if (!IsAccessibleFromAssembly(triggerBaseType))
            {
                continue;
            }

            var concreteTypes = GetConcreteTypes(triggerBaseType, allTypes);

            // Nothing to register if no accessible concrete types were found
            if (concreteTypes.Count == 0)
            {
                continue;
            }

            var baseTypeName = triggerBaseType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var typeArray = string.Join(", ", concreteTypes.Select(t =>
                $"typeof({t.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)})"));
            source.AppendLine(
                $"            TriggerTypeRegistry.Register<{baseTypeName}>(new[] {{ {typeArray} }});");
        }

        source.AppendLine("        }");
        source.AppendLine("    }");
        source.AppendLine("}");

        context.AddSource("TriggerTypeRegistry.g.cs", source.ToString());
    }

    private static List<INamedTypeSymbol> GetConcreteTypes(
        INamedTypeSymbol baseType,
        List<INamedTypeSymbol> allTypes)
    {
        // For enum TTrigger, register the enum type itself (no subtypes)
        if (baseType.TypeKind == TypeKind.Enum)
        {
            return new List<INamedTypeSymbol> { baseType };
        }

        // Find all non-abstract, non-generic types that derive from the base type
        // Only include types that are accessible from the generated module initializer
        var derivedTypes = allTypes
            .Where(t => !t.IsAbstract && t.TypeParameters.IsEmpty)
            .Where(t => !SymbolEqualityComparer.Default.Equals(t, baseType) && IsAssignableTo(t, baseType))
            .Where(IsAccessibleFromAssembly)
            .OrderBy(t => t.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), StringComparer.Ordinal)
            .ToList();

        // If no derived types found, register the base type itself as a fallback
        // (only if the base type itself is accessible)
        if (derivedTypes.Count == 0 && IsAccessibleFromAssembly(baseType))
        {
            return new List<INamedTypeSymbol> { baseType };
        }

        return derivedTypes;
    }

    /// <summary>
    /// Returns true if the type and all its containing types are at least internal,
    /// making them accessible from the generated module initializer class in the same assembly.
    /// </summary>
    private static bool IsAccessibleFromAssembly(INamedTypeSymbol type)
    {
        var current = type;
        while (current is not null)
        {
            switch (current.DeclaredAccessibility)
            {
                case Accessibility.Private:
                case Accessibility.Protected:
                case Accessibility.ProtectedAndInternal:
                    return false;
            }

            current = current.ContainingType;
        }

        return true;
    }

    private static bool IsAssignableTo(INamedTypeSymbol type, INamedTypeSymbol baseType)
    {
        var current = type.BaseType;
        while (current is not null)
        {
            if (SymbolEqualityComparer.Default.Equals(current.OriginalDefinition, baseType.OriginalDefinition))
            {
                return true;
            }

            current = current.BaseType;
        }

        return false;
    }

    private static void CollectTypes(INamespaceSymbol namespaceSymbol, List<INamedTypeSymbol> types)
    {
        foreach (var type in namespaceSymbol.GetTypeMembers())
        {
            types.Add(type);
            CollectNestedTypes(type, types);
        }

        foreach (var nestedNamespace in namespaceSymbol.GetNamespaceMembers())
        {
            CollectTypes(nestedNamespace, types);
        }
    }

    private static void CollectNestedTypes(INamedTypeSymbol type, List<INamedTypeSymbol> types)
    {
        foreach (var nested in type.GetTypeMembers())
        {
            types.Add(nested);
            CollectNestedTypes(nested, types);
        }
    }
}
